# Google Cloud Build configuration for VDP Extractor Service
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vdp-extractor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vdp-extractor:latest'
      - '.'
    
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/vdp-extractor:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/vdp-extractor:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vdp-extractor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vdp-extractor:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '10'
      - '--timeout'
      - '300s'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'

# Specify the machine type for Cloud Build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'

# Artifacts to store
images:
  - 'gcr.io/$PROJECT_ID/vdp-extractor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vdp-extractor:latest'