#!/bin/bash

echo "🔧 n8n 워크플로우 수동 활성화 가이드"
echo "======================================="
echo ""
echo "1. 브라우저에서 n8n 웹 인터페이스 접속:"
echo "   👉 http://localhost:5678"
echo ""
echo "2. 좌측 메뉴에서 'Workflows' 클릭"
echo ""
echo "3. 다음 3개 워크플로우 각각 클릭 후 활성화:"
echo "   📹 YouTube Data API Metadata Collector"
echo "   📸 Instagram oEmbed/Graph API Collector" 
echo "   🎵 TikTok oEmbed + Playwright Scraper"
echo ""
echo "4. 각 워크플로우에서:"
echo "   - 우상단 'Inactive' 토글을 클릭하여 'Active'로 변경"
echo "   - 'Save' 버튼 클릭"
echo ""
echo "5. 활성화 확인:"
echo "   - 모든 워크플로우 상태가 'Active'인지 확인"
echo "   - Webhook URL들이 생성되었는지 확인:"
echo "     • /webhook/youtube-metadata"
echo "     • /webhook/instagram-metadata" 
echo "     • /webhook/tiktok-metadata"
echo ""
echo "✅ 활성화 완료 후 다음 명령으로 테스트:"
echo "curl -X POST http://localhost:3000/api/ingest \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"type\":\"url\",\"content\":\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"}'"