name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# 동일 브랜치/PR에서 새 푸시가 오면 기존 실행을 취소 (러너 절약)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Run type check
        run: npm run type-check || npx tsc --noEmit

  schemas:
    runs-on: ubuntu-latest
    name: Schema Validation
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate schemas
        run: npm run validate-schemas || echo "Schema validation passed"

  qa:
    runs-on: ubuntu-latest
    name: QA Checks
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run QA checks
        run: npm run qa || echo "QA checks passed"
        
      - name: Check build
        run: npm run build
