name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test -- --reporters=default
        
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/

  schemas:
    name: Schema Validation
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate schemas
        run: npm run schemas:check

  contracts:
    name: Contract Tests
    runs-on: ubuntu-latest
    needs: schemas
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run contract tests
        run: npm run test:contracts

  qa:
    name: QA & Security Guards
    runs-on: ubuntu-latest
    needs: contracts
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run type check
        run: npm run type-check
        
      - name: Media Policy Check
        run: npm run ci:media-policy
        
      - name: Accessibility Contrast Check  
        run: npm run ci:a11y
        
      - name: VDP Exposure Guard
        run: npm run ci:vdp-guard
        
      - name: Run Guard Tests
        run: npm test src/__tests__/guards
        
      - name: Check VDP exposure (legacy)
        run: node scripts/check-vdp-exposure.js || true
        
      - name: Validate Problem+JSON (legacy)
        run: node scripts/validate-problem-details.js || true
